### ISSUE TITLE
Add support for node 16

### ISSUE THREAD

**Issue by VladimirCores** [javierbrea/cypress-fail-fast#153]
**Is your feature request related to a problem? Please describe.**
We would like to use node 16 in our project

**Describe the solution you'd like**
Update CFF to use with node 16

**Additional context**
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'cypress-fail-fast@2.2.0',
npm WARN EBADENGINE   required: { node: '10.x || 12.x || 14.x || 15.x' },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.20.3' }
npm WARN EBADENGINE }

**Comment by javierbrea** [comment]
Hi @VladimirCores, you can use the latest version, which already supports node 16
