### ISSUE TITLE
Work with 'retries' configuration property

### ISSUE THREAD

**Issue by Dorious** [javierbrea/cypress-fail-fast#162]
I don't know was that reported yet, but `retries` feature doesn't seem to work.
I would like it to work nicely with https://docs.cypress.io/guides/guides/test-retries#Global-Configuration
Anyway this is great tool and it helps us a lot :P

**Comment by javierbrea** [comment]
Hi @Dorious ,
Could you please provide more details about the way it is not working when you set the `retries` option? In theory, the plugin takes the `retries` option into account and only enables fail-fast when the last retry fails.

**Comment by testingJava2** [comment]
Hello @javierbrea,

It seems that if we set 
````javascript
// cypress.json
{
  "env":
  {
    "FAIL_FAST_ENABLED": false
  }
}
````
and set the fail fast to run only on a dedicated describe or it block
````javascript
describe("Some tests", { failFast: { enabled: true } }, () => {

});
````
then the global `retry` is not applied.

We will then need to re-iterate to Cy that it needs to retry these tests:

````javascript
describe("Some tests", { failFast: { enabled: true }, retries: ###}, () => {

});
````

**Comment by javierbrea** [comment]
Closed due to inactivity
