### ISSUE TITLE
Make number of failed tests configurable

### ISSUE THREAD

**Issue by josefsmrz** [javierbrea/cypress-fail-fast#186]
**Is your feature request related to a problem? Please describe.**
Hi, I would like to use this plugin, because sometimes I encounter test runs where all the tests are failing and this uses a lot of resources. However, I'd like to have the number of failing tests configurable, because it can happen, that a test is failing and I still want to execute the whole test run.

**Describe the solution you'd like**
It would be good to have an env variable where I could set a number of failing tests after which all of the remaining tests should be skipped.

**Comment by javierbrea** [comment]
Hi @josefsmrz ,
Thanks for your suggestion. The new FAIL_FAST_BAIL option is available in [v3.4.0](https://github.com/javierbrea/cypress-fail-fast/releases/tag/v3.4.0)

**Comment by josefsmrz** [comment]
Hi @javierbrea,
looks very good, thanks for the fast implementation! I am currently testing it in our project and I've noticed these messages:
[fail-fast] Enabling skip mode
appear after every failed test. Perhaps this could be replaced by a message counting the number of failed tests so far, something like:
[fail-fast] Failed tests: x/y

BTW seems to work with the test retries (https://docs.cypress.io/guides/guides/test-retries#Configure-Test-Retries), which is great!

**Comment by javierbrea** [comment]
Thanks @josefsmrz,
You're right, that message shouldn't be printed until the plugin actually enables the skip mode. I have opened the #193 issue for fixing it.
