### ISSUE TITLE
Getting this Error(1) "after each" hook in "{root}") and not progressing further

### ISSUE THREAD

**Issue by senthiltr** [javierbrea/cypress-fail-fast#212]
Getting this Error(1) "after each" hook in "{root}") and not progressing further

** Operating system, Node.js an npm versions, or browser version (please complete the following information):**
 - OS: CentOS 7
 - Node.js: v14.16.0
 - npm: 6.14.11
 - Browser: Firefox-91
 - Cypress: 6.4,0

**Additional context**

I given the sample code here.
plugin/index.js:
module.exports = (on, config) => {
  
  const failfastObj = require('cypress-fail-fast/plugin')(on, config);
  console.log('failFast:',failfastObj);
}
support/index.js:
import "cypress-fail-fast";
cypress.json:
env:{
"FAIL_FAST_STRATEGY": "spec",
    "FAIL_FAST_ENABLED": true,
    "FAIL_FAST_BAIL": 1,
}
integration/spec1.js:
I have these below of how my spec file looks like.
describe('test", ()=>{
 before("", ()=>{
   Getting value from fixtures and assign into global variable
  });
beforeEach("", ()=>{
   setting cookies
  })
it("test1", ()=>{
cy.log('Test1");
});
it("test2", ()=>{
cy.log('Test2");
});
.
.
.
});

**Comment by javierbrea** [comment]
Hi @senthiltr, it seems that you have an error in your code: You are calling to `before` and `beforeEach` hooks passing two parameters instead of one. You can check hooks usage examples in the [Cypress docs](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Support-file).

**Comment by senthiltr** [comment]
Thanks for the reply. With that it worked sometime. Sometimes not. I have removed "" from before and beforeEach.
Also now after first failure getting below statements but not starting second testsuite(spec).
[fail-fast] Failed tests: 1/1
[fail-fast] Enabling skip mode

Kindly suggest.
THanks
Senthilkumar TR

**Comment by senthiltr** [comment]
here is my run command.
./node_modules/.bin/cypress run --browser /usr/bin/firefox --env DEFAULT_ENVIRONMENT_NAME=auto_cluster_18313 --spec "spec1.js,spec2.js" --headless true

**Comment by javierbrea** [comment]
Hi again. Are you sure that the issue is related to the usage of this plugin? You could check it uninstalling it completely and then trying again.

**Comment by javierbrea** [comment]
Closed due to inactivity
