### ISSUE TITLE
Option to enable fail-fast only in specific tests or describes

### ISSUE THREAD

**Issue by quad5** [javierbrea/cypress-fail-fast#27]
**Is your feature request related to a problem? Please describe.**

there is a certain percentage where we write test independent of other tests, and dependent of other tests. At the time of writing this request, this plugin fails fast when a test fails in a test file. 

**Describe the solution you'd like**

This request is to only fail on dependent test(s). So some kind of configuration to say fail fast in this `describe` if we want to, but don't fail fast on other test files when a failure occurred.

**Comment by javierbrea** [comment]
Hi @quad5, sorry but I'm not really sure about what do you mean. 

I have thought about adding an option which could make `fast-fail` to be applied only to the rest of tests in the current file or to apply it to all of the rest of files too, as currently. It could work as @brian-mann suggested in [this Cypress issue](https://github.com/cypress-io/cypress/issues/518):

```
FAIL_FAST_STRATEGY: 'spec' | 'run'
```

So, setting a `FAIL_FAST_STRATEGY` as `spec` would make skip tests only in the current file, and setting it as `run` would make skip all tests in the rest of files too.

Please let me know if this option is what you are looking for, so I can reuse this issue to implement it, or it does not match your requirements and you need more control over each specific `describe` or `it`.

**Comment by quad5** [comment]
When we run cypress tests, there are tests that we want to fail fast, and there are tests (in different or same test file) that we don't want it to fail fast. 

You understand my request with this statement: `you need more control over each specific 'describe' or 'it'`

Thanks

**Comment by chuckadams** [comment]
One thing I would like in my test suite would be a "sanity" test that runs first, and if that particular test fails -- and only that test -- all other tests are skipped.  Any other failures are treated normally.  Similar to what phpunit does with `@depends`, but without having to implicitly mark every test.

**Comment by javierbrea** [comment]
Hi @chuckadams,

I think that your scenario could be solved with the options I am thinking to implement for this issue _(the #33 one is related to fail-fast parallel executions in CI)_.

Once implemented, each `describe` or `it` would accept next options object:

```js
{
  failFast: {
    enabled: true //false
  }
}
```

So, you could achieve what you are describing as:

```js
describe("All tests", {
  failFast: {
    enabled: false, // Next tests and describes will inherit this value
  },
}, () => {
  it("sanity test", {
    failFast: {
      enabled: true, // Overwrite previously defined options
    },
  }, () => {
    // Will skip the rest of tests if this one fails
    expect(true).to.be.true;
  });

  it("second test",() => {
    // Will continue if this one fails, as it inherits the options in the parent `describe`
    expect(true).to.be.true;
  });

  it("third test",() => {
    // Will continue if this one fails, as it inherits the options in the parent `describe`
    expect(true).to.be.true;
  });
});
```

Thanks for your feedback! 🙂

**Comment by MuckT** [comment]
@javierbrea I would find this incredibly useful. I've set-up some e2e tests for my project that walk through a process and if test 2 fails there's no point in running the remaining it blocks. Then I have other tests where I would like all the tests to run regardless of a fail in the spec.
