### ISSUE TITLE
Argument of type '{ failFast: { enabled: boolean; }; }' is not assignable to parameter of type 'SuiteConfigOverrides'.

### ISSUE THREAD

**Issue by Magg1808** [javierbrea/cypress-fail-fast#275]
Hello,

I'd like to ask if you have encountered the problem of not being able to add failFast property to "describe" call? In the case of "it", it works fine.

![1](https://user-images.githubusercontent.com/49453382/205951408-2c659561-9c33-4b39-95b3-199536b6fbba.png)
![2](https://user-images.githubusercontent.com/49453382/205951505-acf59cb0-4b84-48a5-9113-d55c2aefa8c6.png)

Cypress v.11.2.0

Sorry if this is the wrong place for this question.

Best,
Magda

**Comment by javierbrea** [comment]
Hi @Magg1808 ,
Thanks for the notice, this is the right place for this type of questions, of course 😉 . The plugin tests are checking the TypeScript declarations, but they don't include Cypress 11 for the moment, so it is probably related to Cypress version. I will add Cypress 11 and 12 to the test batteries as soon as possible.

**Comment by Magg1808** [comment]
Hello again, 

thanks for reply. Could the problem of using `import `instead of `require `to download this tool also be related to the Cypress version?
When I use this syntax `import cypressFailFast from 'cypress-fail-fast/plugin';` or `import { cypressFailFast } from 'cypress-fail-fast/plugin';`
and then   
setupNodeEvents(on, config) {
      cypressFailFast(on, config);
      return config;
      }
I get this error:
![1 2](https://user-images.githubusercontent.com/49453382/206223741-87408a54-47b9-46e9-bd4a-025a57446611.png)

Maybe I converted it wrong?

**Comment by javierbrea** [comment]
> Hello again,
> 
> thanks for reply. Could the problem of using `import `instead of `require `to download this tool also be related to the Cypress version? When I use the syntax `import cypressFailFast from 'cypress-fail-fast/plugin';` or `import { cypressFailFast } from 'cypress-fail-fast/plugin';` in the cypress.config.ts file and then
> 
> ```
> setupNodeEvents(on, config) {
>       cypressFailFast(on, config);
>       return config;
>       }
> ```
> 
> I get this error: ![1 2](https://user-images.githubusercontent.com/49453382/206223741-87408a54-47b9-46e9-bd4a-025a57446611.png)
> 
> Maybe I converted it wrong?
> 
> With this syntax it works fine:
> 
> ```
> setupNodeEvents(on, config) {
>  // eslint-disable-next-line @typescript-eslint/no-var-requires, unicorn/prefer-module
> require('cypress-fail-fast/plugin')(on, config);
>  return config;
> }
> ```

No, that seems related to the way you are importing the plugin. Note that in TypeScript the plugin has to be imported using `import cypressFailFast = require("cypress-fail-fast/plugin");`, [as described in the documentation](https://github.com/javierbrea/cypress-fail-fast#usage-with-typescript).

**Comment by Magg1808** [comment]
> No, that seems related to the way you are importing the plugin. Note that in TypeScript the plugin has to be imported using `import cypressFailFast = require("cypress-fail-fast/plugin");`, [as described in the documentation](https://github.com/javierbrea/cypress-fail-fast#usage-with-typescript).

Thank you. Unfortunately, this method of importing doesn't work for me either. When I run the tests I get an error

```
     TypeError: The following error originated from your test code, not from Cypress.
  > Cannot read properties of undefined (reading 'localeData')
```
even if i have commonjs set in config.json

"compilerOptions": {
    "module": "commonjs"
  }
