### ISSUE TITLE
Request @types/cypress-fail-fast

### ISSUE THREAD

**Issue by jeff00seattle** [javierbrea/cypress-fail-fast#37]
Provide **typescript** transition for this module.

**Comment by javierbrea** [comment]
Hi @jeff00seattle,
Thanks for your feedback! I have just released the [version v1.3.0](https://github.com/javierbrea/cypress-fail-fast/releases/tag/v1.3.0), which includes TypeScript declarations and instructions to install it if you are using TypeScript in the Cypress plugins file.

**Comment by jeff00seattle** [comment]
Thank you, checking it out.
