### ISSUE TITLE
Before hook from spec is called in headless mode

### ISSUE THREAD

**Issue by Tinekk** [javierbrea/cypress-fail-fast#52]
**Is your feature request related to a problem? Please describe.**
Before hook's implemented in spec files (eg. DB setup) are still called after failure. It should be skipped to save CI time.

**Describe the solution you'd like**
When SHOULD_SKIP_TASK flag is set to true - it should not run spec's before hook.

**Comment by javierbrea** [comment]
Hi @Tinekk, thanks for your feedback!

A possible solution could be to add another check point using a cypress `before` hook, but this would not work for headed runs, where global `before` hooks are executed only once.

Another solution could be to wrap the `Cypress.runner.onRunnableRun` method adding the extra `SHOULD_SKIP_TASK` check to it, but this could be too "intrusive" in Cypress internals, and may be broken in next Cypress releases or may have another unexpected effects, so please let me think about the better approach.

**Comment by Tinekk** [comment]
Hello, won't first solution work?

If you are in headed mode, then always clear flag in `before` hook, then check the flag only in `beforeEach`.
If you are in headless mode then always check the flag in both `before` and `beforeEach` hook, never reset the flag.

**Comment by javierbrea** [comment]
> Hello, won't first solution work?
> 
> If you are in headed mode, then always clear flag in `before` hook, then check the flag only in `beforeEach`.
> If you are in headless mode then always check the flag in both `before` and `beforeEach` hook, never reset the flag.

Yes, it will work, but only for headless mode. In headed mode `before` hooks will continue being executed
