### ISSUE TITLE
Retries property is missing from the TestConfigOverrides implemenation

### ISSUE THREAD

**Issue by DeeGeeMan** [javierbrea/cypress-fail-fast#69]
I am seeing an error when using TypeScript in WebStorm IDE.

**Error message:**
Property 'failFast' is missing in type '{ retries: { runMode: number; openMode: number; }; }' but required in type 'TestConfigOverrides'.

**Error Image:**
![image](https://user-images.githubusercontent.com/21670040/112351092-f7cc9280-8c9f-11eb-9ace-cd37a1aa4bf9.png)

**Comment by javierbrea** [comment]
Hi @DeeGeeMan,

It has been fixed in [release v2.2.1](https://github.com/javierbrea/cypress-fail-fast/releases/tag/v2.2.1).

Thanks for your feedback! 🙂
